REPO_TAGLINE: Academic Research Journal
ASSETS_DIR: Concepts * Theory * Simulation tools
CTA_TEXT: Website
THEME: 
SITE_URL: http://high-energy-physics-research.github.io/academic-research-journal

BG_1: "#101826"
BG_2: "#2A1E14"
TEXT_MAIN: "#FFF7ED"
TEXT_MUTED: "#E7D6C2"
ACCENT: "#FB923C"
CARD_RADIUS: "18"